### ISSUE TITLE
Root and xuser passwords are incorrect

### ISSUE THREAD

**Issue by moeinovic** [qeeqbox/docker-images#3]
Passwords are incorrect and are displayed with the following error
su: Authentication failure

**Comment by giga-a** [comment]
Hey @moeinovic if you figure out what's the issue, raise a Pull Request. Otherwise, i will take a look next week!

**Comment by giga-a** [comment]
@moeinovic Where does it say `su: Authentication failure`? Could you tell me the steps to reproduce it?
